# Generated by Django 3.0.6 on 2020-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.NullBooleanField(),
        ),
    ]
